export interface Button {
  className?: string,
  style?: React.CSSProperties,
  children?: React.ReactNode,
  content?: React.ReactNode,
  variant?: 'base' | 'outline' | 'dashed' | 'text',
  theme?: 'default' | 'primary' | 'warning' | 'success' | 'error',
  shape?: 'rect' | 'round',
  disabled?: boolean,
  loading?: boolean,
  block?: boolean,
  icon?: string,
  size?: 'normal' | 'small' | 'large',
  pureIcon?: boolean,
  onClick?: (e: React.MouseEvent) => void,
}
